### PR TITLE
chore(project): Renamed to swan-example

### PR DESCRIPTION
**Pull request by RWOverdijk**
chore(project): Renamed to swan-example

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@VMBindraban review please.

**Comment by VMBindraban** [comment]
:+1:

**Comment by VMBindraban** [comment]
Don't forget https://github.com/SpoonX/swan-cli/blob/master/lib/config.js#L37

**Comment by RWOverdijk** [comment]
Nice catch.

**Comment by RWOverdijk** [comment]
Done.

**Pull request merged**
